defaults:
  - scope:
      path: ""
      type: "seniors"
    values:
      layout: senior
      sidebar: true
  - scope:
      path: ""
      type: "pages"
    values:
      layout: default
  - scope:
      path: ""
      type: "posts"
    values:
      layout: default
